Repository SovereignCloudStack/website, pull requests merged in 2023-05, with the labels that each got.

#632 Add CVE-2023-2088 advisory: SCS not affected.
  _i18n/de/_posts/blog/2023-05-10-cve-2023-2088.md
  _i18n/en/_posts/blog/2023-05-10-cve-2023-2088.md
Labels: bug, documentation, security

#638 Talk b/w Johan and Kurt will be in (EN).
  _i18n/de/summit2023.md
  _i18n/en/summit2023.md
Labels: documentation

#650 Create FriederikeZelke
  _members/FriederikeZelke
Labels: Community

#654 Rename to .md. stay -> keep.
  _members/FriederikeZelke.md
Labels: Community

#666 Add matofeder community profile
  _assets/images/matofeder.png
  _members/matofeder.md
Labels: Community
