Repository SovereignCloudStack/website, pull requests merged in 2023-06, with the labels that each got.

#667 Add blog post - SCS container registry migration and upgrade
  _assets/images/blog/registry_migration.png
  _assets/images/blog/registry_migration_velero.png
  _i18n/de/_posts/blog/2023-05-30-registry-migration-upgrade.md
  _i18n/en/_posts/blog/2023-05-30-registry-migration-upgrade.md
Labels: Container, Sprint Dublin

#669 Create Cloud Expo 2023
  _i18n/de/_posts/blog/2023-06-05-cloud-expo-2023.md
  _i18n/en/_posts/blog/2023-06-05-cloud-expo-2023.md
Labels: Community

#673 Link to 2023 summit not 2024.
  _data/conferences_de.yml
Labels: documentation, Community

#681 Add AOV logo&link to list of SCS providers.
  _assets/images/logo-aov.svg
  _data/provider.yml
Labels: documentation, enhancement
