Repository SovereignCloudStack/website, pull requests merged in 2024-10, with the labels that each got.

#1029 Blog post on adjustements for SCS compliance.
  _i18n/de/_posts/blog/2024-10-14-cert-adapt-example.md
  _i18n/en/_posts/blog/2024-10-14-cert-adapt-example.md
Labels: documentation, standards

#953 Add blog post "Demystifying Gaia-X Credentials"
  _assets/images/blog/gx-credentials/gx-credentials-creation.png
  _assets/images/blog/gx-credentials/gx-credentials-verification.png
  _assets/images/blog/gx-credentials/gx-lrn-credential-creation.png
  _assets/images/blog/gx-credentials/gx-lrn-credential-structure.png
  _assets/images/blog/gx-credentials/gx-participant-lrn-reference.png
  _assets/images/blog/gx-credentials/gx-participant-so-relation.png
  _assets/images/blog/gx-credentials/gx-verifiable-presentation.png
  _i18n/de/_posts/blog/2024-10-15-demystifying-gaia-x-credentials.md
  _i18n/en/_posts/blog/2024-10-15-demystifying-gaia-x-credentials.md
Labels: SCS-VP10

#1034 Press release on the Forum SCS-Standards.
  _assets/images/forumscs-1-474x324.jpg
  _i18n/de/_posts/announcements/2024-10-23-osba-forum-scs-standards.md
  _i18n/en/_posts/announcements/2024-10-23-osba-forum-scs-standards.md
Labels: Community
