Repository SovereignCloudStack/website, pull requests merged in 2024-05, with the labels that each got.

#935 Feat/remove ipcei2
  _data/quotes.yml
  _i18n/de.yml
  _i18n/de/home/ipcei.md
  _i18n/en.yml
  _i18n/en/home/ipcei.md
Labels: bug

#917 Add blog post on making a cluster SCS-compliant
  _assets/images/blog/yaook_architecture_overview.svg
  _i18n/de/_posts/blog/2024-05-13-cost-of-making-an-openstack-cluster-scs-compliant.md
  _i18n/en/_posts/blog/2024-05-13-cost-of-making-an-openstack-cluster-scs-compliant.md
Labels: SCS-VP10

#949 Add "Ausgabe"
  _data/news_de.yml
Labels: documentation

#950 Add SCS Summit 2024 and DFN Webinar.
  _data/conferences_de.yml
Labels: documentation
